### ISSUE TITLE
Black Screen On Ubuntu 14.04 using latest Intel Drivers

### ISSUE THREAD

**Issue by jyapayne** [away3d/away3d-core-openfl#15]
When I compile an example from away3d-core-openfl, everything compiles fine and a window opens up. The window is completely black, but the terminal shows output, which leads me to believe something is wrong with the display.

I tested on my Mac OS X 10.9.5 and it worked fine with the Intel Drivers.

**Comment by ibilon** [comment]
I tried on two ubuntu and I had a black screen too, sadly I also had a black screen on two openSUSE, one with open source driver and the other one with proprietary amd driver.
So this may be a linux problem. (tried why and without `-Dnext`)

I looked quickly at apitrace https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown, using it to trace Basic_View, both the replay and export to pngs were all black.
Also the HerokuShader sample of lime and openfl works.

**Comment by mauvecow** [comment]
Investigated this a bit on OpenFL 3.0 as I'm having the same problem on my nvidia driver, and -Dlegacy isn't helping. Haven't had time to do a full check, but I know what's causing this now.

apitrace has this little gem in it:
    2393 glClearDepth(depth = 0.007812501848093234)

Clearly not correct. I tracked this down to lime's graphics.openfl.GL library and the value is the correct '1' all the way up until it calls the native lime_gl_clear_depth. I'm guessing this has something to do with an incorrect function call.

Dummying out the call to clearDepth either here or in OpenFL causes Basic_View and Basic_Fire to run and display correctly.

Guessing the function parameter isn't being passed to native correctly, like it's expecting a double and getting a float? I'll do a little more checking on this later.

**Comment by Greg209** [comment]
Hmm... Interesting that you've managed to track down a potential culprit. I took that value and passed it to a Float/Double to Hex/Binary converter and it seems like a fairly round number in hex terms 0x3c000002 or something like that - even though it didn't seem to match any particular enum value for GL. That lead me to think it was something float conversion that could be the problem.

Looking at line https://github.com/openfl/openfl/blob/master/openfl/display3D/Context3D.hx#L93 I noticed that the Context3D parameter for the clear method takes the depth as a Float rather than an Int. 

Any chance you could simply try changing the param to an Int - just in case it's getting converted and see if that works? I've tried in VirtualBox running Ubuntu but I get loads of crud output from the virtualBox graphics drivers or a seg fault.

See if that makes a difference or not. I really need to setup my ageing PC with a Ubuntu partition to test things.

**Comment by mauvecow** [comment]
Nah, the problem is that lime_gl_clear_depth is calling glClearDepth() with the wrong parameter type (GLclampf instead of GLclampd, which is 4 byte float vs 8 byte double). Compare:

https://github.com/openfl/lime/blob/master/project/src/graphics/opengl/OpenGLExtensions.h#L167
https://www.opengl.org/sdk/docs/man2/xhtml/glClearDepth.xml

Whoops.

I changed this in my lime and it fixes some of the problems with Away3D here, so I'm going to throw them a pull request once I do a little more digging. (in the meantime you can safely kill that call, it seems to be '1' always and that's the actual default.)

Of the other demos, though, SkyBox and MD5Animation are not rendering correctly, going to look into those while I'm here.

**Comment by Greg209** [comment]
Interesting - I was just looking at some html5 rendering issues and that seems to fix a few things if I remove the ClearDepth call. Perhaps it's not necessary if calling clear with the appropriate bits. I perhaps need to investigate whether it's needed at all. 

Thanks for continuing to look into this - you help is much appreciated.

**Comment by Greg209** [comment]
Fixed an Android issue I noticed yesterday as well - This is great!!!!!

**Comment by mauvecow** [comment]
https://github.com/openfl/lime/pull/464 Fix for that should be in Lime now.

Still looking into the other problems, not a clue what's going on there yet but suspecting information is being passed to the shaders incorrectly.

**Comment by mauvecow** [comment]
A small update. for OpenFL3 native target related problems:

- Skybox isn't working because, when generating mipmaps, OpenFL3's BtimapData.__drawGL() is not rendering correctly. It uses framebuffers to draw the texture scaled offscreen. (it's definitely somewhere in this function)
- MD5Animation appears to be not rendering correctly because the shadowmapping creates an offscreen rendertarget, and setRenderToTexture is not working correctly. (commenting out all shadowmap stuff makes it work fine.) (Not actually sure if that function is the culprit or if something related is, but it seems likely)

So something's goofed with framebuffers on native GL right now, and strictly speaking this is probably not an Away3D problem. Going to be a little busy but I'll look into it some more soon.

**Comment by jcward** [comment]
Just chiming in to say I'm not seeing any issues mentioned in this thread on Ubuntu 14.04 on my Acer chromebook. Everything (Basic_View, MD5Aniation, SkyBox) seems to be working fine with neko, native, and html5.

Actually, MD5 in html5 has some minor glitches:

![image](https://cloud.githubusercontent.com/assets/2192439/10194895/4705e47e-6748-11e5-9819-679c4335da71.png)

But not native. Generally seems to be working for me.

**Comment by ibilon** [comment]
Retried `Basic_View` and `Intermediate_MD5Animation` on ubuntu with latest away3d/openfl/lime and it's working for me too.

**Comment by Greg209** [comment]
Thanks for testing guys. As that's two good tests I'm gonna mark this as closed. Any additional issues can be raised separately.
